### ISSUE TITLE
Issue with Typescript type

### ISSUE THREAD

**Issue by bmeverett** [swiftcarrot/react-input-color#41]
Hi there 👋 

When I try to use this component with typescript I get the following error: 

<img width="582" alt="image" src="https://user-images.githubusercontent.com/3941006/74980009-bb27cb00-53fd-11ea-8a56-c78e2b8e896b.png">

Taking a look at the types, it looks like you are exporting type void for the state prop, which is what it seems to be complaining about.
`export default class InputColor extends Component<InputColorProps, void> {}`

Would you be able to change `void` to `any`? You could also export it as a function since it looks like it's a functional component anyway
`export default function InputColor(props: InputColorProps)`

I would be happy to make a PR for this as well!

**Comment by wangzuo** [comment]
Sure, pr welcome
