### ISSUE TITLE
Example of Multiple Color Inputs in Single Form

### ISSUE THREAD

**Issue by jwtd** [swiftcarrot/react-input-color#43]
The input props don't accept an ID or name attributes. Adding one triggers a typescript error. How do you assign an identity when multiple color pickers are used in a single form? The goal is to create a single method to handle all color changes vs a separate color handler for each input.

```
const allColors = {
  colorA: '',
  colorB: '',
  ...lots more...
  colorN: ''
};
const handleColorChange = (e => {
   allColors[e.target.name] = e.target.value;
});
```

**Comment by wangzuo** [comment]
check https://codesandbox.io/s/magical-tdd-9cbjw
